name: Update algolia indices when data changes

on:
  push:
    branches:
      - main
    paths:
      - 'promessas_data/**'

env:
  ALGOLIA_APP_ID: ${{ env.ALGOLIA_APP_ID }}
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node Install
        run: npm i
      - name: Dump json
        run: npm run dump-json > data.json
      - name: Reindex PS
        run: PARTY=ps node scripts/reindex_algolia.js
      - name: Reindex AD
        run: PARTY=ad node scripts/reindex_algolia.js
