name: Update algolia indices when data changes

on:
  push:
    branches:
      - main
    paths:
      - 'promessas_data/**'

env:
  ALGOLIA_APP_ID: ${{ vars.ALGOLIA_APP_ID }}
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node Install
        run: npm i
      - name: Reindex PS
        env:
          PARTY: ps
        run: node scripts/reindex_algolia.js
      - name: Reindex AD
        env:
          PARTY: ad
        run: node scripts/reindex_algolia.js
